# Generated by Django 3.2 on 2021-07-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Subcategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
