# Generated by Django 3.2 on 2021-07-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('query', models.CharField(max_length=1000)),
            ],
        ),
    ]
