# Generated by Django 3.2 on 2021-07-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='long_desc',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
